### ISSUE TITLE
Guice Exceptions (with line breaks)  don't show up correctly in Console

### ISSUE THREAD

**Issue by hartmut27** [eclipse-jetty/eclipse-jetty-plugin#10]
When I start the jetty web appliaction and as soon as some Guice errors occur, they don't show a correct line break in the eclipse console. This means, the whole stack trace is put in _one single line_. 

Something is special to Guice error message line breaks. On the other side, this problem does only occur if I run it with eclipse-jetty-plugin. 

Instead of a line break, a **<|<|** token is shown. I guess this corresponds to CRLF somehow?

Example:
com.google.inject.ProvisionException: Unable to provision, see the following errors:**<|<|**1) Error injecting constructor, javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, ...

**Comment by derkoe** [comment]
I just tried that out and yes the Guice errors are messed in Jetty console. 

**But** then I deployed the app directly to Jetty (without Eclipse and plugin) and the format is still the same. Seems that Jetty's logger messes with the format.

I have searched the Jetty bug tracker and there it is: [Bug 414763 - StdErrLog makes multiline messages unreadable ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414763)

**Comment by hartmut27** [comment]
Thank You very much. Indeed, jetty itself does the escaping of logged lines by default. Great You found out!

Then, adding e.g. VM arguments 

    -Dorg.eclipse.jetty.util.log.stderr.ESCAPE=false

to the Jetty run configuration solves the problem entirely. :+1:
