### ISSUE TITLE
Hot Deploy

### ISSUE THREAD

**Issue by d4v1dv00** [eclipse-jetty/eclipse-jetty-plugin#12]
How do I enable Hot Deploy using the plugin? Thanks.

**Comment by derkoe** [comment]
What do you mean by hot deploy?
- Eclipse changes classes on the fly without restarting
- If you want to have real reloading - use JRebel
- If you want to restart the application on code changes - use the IDE. For Eclipse: http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fviews%2Fdebug%2Fref-terminaterelaunch.htm

**Comment by derkoe** [comment]
No further infos provided - will close this issue.
