### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by thred** [eclipse-jetty/eclipse-jetty-plugin#14]
Add support for web sockets. 

https://github.com/klausbayrhammer/jetty-websockets can be used as test project.

**Comment by arwilliamson** [comment]
I am getting the same problem.

I added in all the JARs from $JETTY_HOME/lib, $JETTY_HOME/lib/websocket, $JETTY_HOME/lib/annontations yet still get this error.   What am i missing?

```
javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable
	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:146)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:65)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
```

**Comment by PaniniGelato** [comment]
It seems like it is missing a "Enable Websocket Support CHECKBOX" in the options pannel, so run-jetty-run never load websocket libs and disable websocket module.

**Comment by derkoe** [comment]
First, this is not run-jetty-run. We are Eclipse Jetty (a competitor). 
Second, this is a feature request - so yes, it is not yet implemented.

**Comment by arwilliamson** [comment]
@derkoe are there any plans to implement that flag?   Or what is your recommended work around?

thanks

**Comment by PaniniGelato** [comment]
Sorry for mistaken.
@arwilliamson I am playing websocket with Eclipse Tomcat Server. 
Or you can run an embed jetty like below:
```
public static void main( String[] args ) throws Exception {
        Server server = new Server( 8080 );
        ServletContextHandler context = new ServletContextHandler();
        //some config here
        ......
        //init websocket here
        WebSocketServerContainerInitializer.configureContext( context );       
        //start server
        server.start();
        server.join(); 
}
```
