### ISSUE TITLE
Error on use jetty 9.3.0

### ISSUE THREAD

**Issue by josivan** [eclipse-jetty/eclipse-jetty-plugin#15]
I have updated to jetty-distribution-9.3.0.v20150612 and when I tried to run the jetty I got the message:

"Failed to resolve Jetty dependencies: [.*\/lib\/jsp\/.*\.jar]"

I have downgraded to the previous version of jetty (9.2.11).

Can you help me with that message?

Thanks

@update on 18/06. I analysed the code and I have noticed that line 38 of class net/sourceforge/eclipsejetty/jetty9/Jetty9LibStrategy.java might be the problem.

**Comment by mpetris** [comment]
"The 9.2 release has switched to using the Apache version of Jasper for JSP and JSTL" so everything is in apache-jsp and apache-jstl and the directory "lib/jsp" isn't available anymore.

**Comment by quartex** [comment]
Hi, I have the same problem with 9.3.3, I try to rename the folder (and duplicate it) but it does not work. Do you try to recompile the plugin or ..... to fix it ?
That's a shame for this problem because this is a great plugin !!
Thank you very much

**Comment by derkoe** [comment]
It seems impossible to launch Jetty 9.x versions a similar manner. When I launch 9.2 with the libs in apache-jsp then JSPs won't work. This seems to be unfixable.

**Comment by mpetris** [comment]
Sorry my earlier comment was misleading. It works if you stick with the libs/jsp for 9.2 and use lib/apache-jsp for 9.3. Obviously this involves separate JettyLibStrategies. I gave it a try and issued a pull request. The code works for my tests but maybe you want to have it in a different style. Anyway thanks for this great plugin! BTW I tested the WebSocket feature and it works very well.

**Comment by derkoe** [comment]
See pull request #18
