### ISSUE TITLE
update embedded Jetty to 9

### ISSUE THREAD

**Issue by gimoh** [eclipse-jetty/eclipse-jetty-plugin#22]
With the default v8 I'm getting exceptions like `oeja.AnnotationParser:EXCEPTION` when using Java 8 language features (like lambdas).

Everything works fine with an external Jetty 9.3, it's just more difficult to setup in a team environment.

I can submit a PR, just let me know if that sounds OK.

**Comment by lucidfox** [comment]
Any progress on this?

**Comment by derkoe** [comment]
There was an attempt here #29 - this just needs formatting and we could mergee

**Comment by gk-brown** [comment]
This seems to be done. I installed in Eclipse Oxygen yesterday from the [update site](http://eclipse-jetty.github.io/update/) and found that 9.3 is the currently bundled version.

**Comment by derkoe** [comment]
Changed with Release 4.0.0
