### ISSUE TITLE
Hot deploy function not work well with mars.1

### ISSUE THREAD

**Issue by shadowedge** [eclipse-jetty/eclipse-jetty-plugin#23]
I found that when I use [Eclipse Mars.1], started jetty-server in debug  mode(F11)，everytime I changed some code and save(recompile) the java  file，the server cannot auto deploy at all. Even if I type [r] key  in console  to force restart server，the new code still not effective at all.   
But everything works(nearly the same workspace，the same project，same JDK or config...) well in  [Eclipse Luna SR2].
The issue apears with 3.8 and 3.9，not try for earlier version.

**Comment by derkoe** [comment]
I'm also using Mars.1 (4.5.1) and everything works. Please check if you have deactivated "Build Automatically".  And also check if the .class files change the timestamp on compile - maybe there's some other config problem.

**Comment by shadowedge** [comment]
YES,it's the problem with "build automatically", thank you very much!!
