### ISSUE TITLE
LoginService not instancied

### ISSUE THREAD

**Issue by woulf** [eclipse-jetty/eclipse-jetty-plugin#28]
Hello there, i'm configuring a login service in the WebAppContext as i do in my usual jetty setup
```
<Configure id="wac" class="org.eclipse.jetty.webapp.WebAppContext">
   <Call name="prependServerClass">
    <Arg>-org.eclipse.jetty.server.handler.ContextHandler</Arg>
  </Call>
  <Call name="prependServerClass">
    <Arg>-org.eclipse.jetty.servlet.FilterHolder</Arg>
  </Call>
  <Call name="prependServerClass">
    <Arg>-org.eclipse.jetty.servlet.ServletContextHandler</Arg>
  </Call>
  <Call name="prependServerClass">
    <Arg>-org.eclipse.jetty.servlet.ServletHolder</Arg>
  </Call>
	<New id="whatever" class="org.eclipse.jetty.plus.jndi.Resource">
		<Arg></Arg>
		<Arg>jdbc/whatever</Arg>
		<Arg>
				<New class="com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource">
				 <Set name="Url">jdbc:mysql://dbip:3306/dbname</Set>
				 <Set name="User">username</Set>
				 <Set name="Password">password</Set>
				</New>
		</Arg>
	</New>
	<Call name="addBean">
		<Arg> 
			<New class="org.eclipse.jetty.security.JDBCLoginService">
			  <Set name="name">gateway_jndi</Set>
			  <Set name="config">absolutepathtotherootofmyprojet\jdbcRealm.properties</Set>
			</New>
		</Arg>
	</Call>
</Configure>
```

and while it work perfectly on my "full" jetty here i get this error on start

> No LoginService for org.eclipse.jetty.security.authentication.FormAuthenticator@46c670a6 in org.eclipse.jetty.security.ConstraintSecurityHandler@59fc684e
 
i have activated JNDI support in the plugin run config.
the only difference is i'm using the jetty-9.3.10 jar in the plugin while my "full" is a 9.3.2 docker container.

Any clue?

**Comment by derkoe** [comment]
Did you add the config file to the "Jetty Context Configuration" in the "Options" tab of the run configuration?

**Comment by woulf** [comment]
yes i did, managed to avoid this error by using:

```
	<Get name="securityHandler">
		<Set name="loginService">
			<New class="org.eclipse.jetty.security.JDBCLoginService">
			  <Set name="name">gateway_jndi</Set>
			  <Set name="config">path\jdbcRealm.properties</Set>
			</New>
		</Set>
	</Get>
```

instead (for some reason?) but now i'm getting an error:

>WELD-001300: Unable to locate BeanManager

like if either:

```
	<New id="BeanManager" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg> <Ref refid="wac"/> </Arg>
        <Arg>BeanManager</Arg>
        <Arg>
            <New class="javax.naming.Reference">
                <Arg>javax.enterprise.inject.spi.BeanManager</Arg>
                <Arg>org.jboss.weld.resources.ManagerObjectFactory</Arg>
                <Arg/>
            </New>
        </Arg>
    </New>
```
in my jetty context or:

```
    <resource-env-ref>
        <resource-env-ref-name>BeanManager</resource-env-ref-name>
        <resource-env-ref-type>javax.enterprise.inject.spi.BeanManager</resource-env-ref-type>
    </resource-env-ref>
```
in my web.xml wasn't used.
I also switched to jetty 9.3.2 in the plugin to be sure it wasn't version related.

**Comment by woulf** [comment]
Ok somy project has been configured to be compiled by jenkins, the whole maven part isn't working in eclipse so my target folder is missing most of the ressources... i'll have to get things right on my side, not a jetty plugin problem.

**Comment by derkoe** [comment]
Is it this problem? 
https://stackoverflow.com/questions/27666681/weld-001300-when-trying-to-lookup-beanmanager-by-jndi

**Comment by woulf** [comment]
yes that is the problem but that's logical: my whole webapp folder is empty in the local target folder of my project.
I haven't setup eclipse to properly build the project since it was built by jenkins, using maven, until now... i'm trying to fasten my developpement process by using a local jetty for debug but it will need a proper project to run ^^ thanks anyway!
