### ISSUE TITLE
jsp folder location changes in Jetty 9.4.x

### ISSUE THREAD

**Issue by marty-cz** [eclipse-jetty/eclipse-jetty-plugin#39]
Hi Eclipse Jetty plugin devs,

I have noticed that Jetty distribution 9.4.x has different location of **jsp** folder in **lib** folder (now it is called **apache-jsp**).

The problem is same as already closed issue #15 for Jetty 9.3.x.

Can you please add support for version 9.4.x as well?

Thank you,
Martin

**Comment by stuban** [comment]
Actually the (default) jsp implementation changed since approx. 9.2.3
I have created a pull request #47 containing a workaround.

**Comment by derkoe** [comment]
Fixed in #47
