### ISSUE TITLE
Restart/redeploy jetty on project build on code changes

### ISSUE THREAD

**Issue by gsitgithub** [eclipse-jetty/eclipse-jetty-plugin#41]
This is not a bug, but aren't we are in development mode where we changes code again and again.
It would rather easy for continues code changes to automatically restart/reload/redeploy web app.
It would be helpful if considered.

Thanks in advance

**Comment by derkoe** [comment]
I think this should be handled by the framework (like [Tapestry](https://tapestry.apache.org/) or [Spring Dev Tools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html)) or other tools like JRebel.
