### ISSUE TITLE
Site no worked

### ISSUE THREAD

**Issue by victormania** [eclipse-jetty/eclipse-jetty-plugin#46]
I can´t dowload to http://eclipse-jetty.github.io/update/

**Comment by froque** [comment]
That link is meant to be used in Eclipse. See: http://help.eclipse.org/2018-12/index.jsp?topic=/org.eclipse.platform.doc.user/tasks/tasks-127.htm

the url points to this github project: https://github.com/eclipse-jetty/eclipse-jetty.github.io/tree/master/update

If you just want to manually download, just checkout the releases: https://github.com/eclipse-jetty/eclipse-jetty-plugin/releases
