### ISSUE TITLE
Maven dependencies are not resolved with jdk11

### ISSUE THREAD

**Issue by geoffreyharding** [eclipse-jetty/eclipse-jetty-plugin#48]
When using JDK9+ as the project execution environment, maven dependencies are not added to the classpath of the Jetty Webapp plugin.

JDK 1.8 : The dependencies tab shows all maven dependencies of the project.
JDK 11 : The dependencies tab is empty (no matter which checkboxes are selected).  In the classpath tab, maven dependencies is not visible.

Is there a known workaround for this issue?

**Comment by venushka** [comment]
Had the same issue @geoffreyharding.

I have raised a PR #49 with a possible fix, I've tested the launch configuration screens and launching a Jetty webapp, and seems to bring the classpath as expected.
